### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by sklipnoty** [thmoa/tex2shape#12]
Can we expect python 3 support?

From what I saw the requirements doens't work either? Chumpy (latest) is not support on python 3?

Python 2.7 is EoL it doesn't make sense to keep using it? 

Workaround for Chumpy:
pip install git+https://github.com/scottandrews/chumpy.git@fe51783e0364bf1e9b705541e7d77f894dd2b1ac

`if sys.version_info[0] == 3:
    import _pickle as pkl
else:
    import cPickle as pkl`

This leads to the error:

`    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 350: character maps to <undefined>`

**Comment by thmoa** [comment]
Feel free to submit a PR.
