### ISSUE TITLE
How do you generate the canonical UV maps in your papers

### ISSUE THREAD

**Issue by wangfudong** [thmoa/tex2shape#14]
Hi thmoa,
Thanks for your great program that helps me a lot.
I have noticed that there were some canonical UV maps as templates used in a series of your papers, such as,

> [1] Tex2Shape: Detailed Full Human Body Geometry From a Single Image
> [2] Video Based Reconstruction of 3D People Models
> [3] Detailed Human Avatars from Monocular Video

where the UV maps look like
![image](https://user-images.githubusercontent.com/23078915/96097745-e66aa780-0f03-11eb-91b2-b3d360c28018.png)
![image](https://user-images.githubusercontent.com/23078915/96097798-f97d7780-0f03-11eb-80b7-2c248f06d875.png)
![image](https://user-images.githubusercontent.com/23078915/96097915-1dd95400-0f04-11eb-9338-a129ab7230cc.png)

I guess all of them are the same UV maps since they have similar shapes and body-partitions.

I want to know what methods/tools/softwares did you used to generate this UV map. Did you use Blender/Maya? 

Thanks~

**Comment by thmoa** [comment]
It comes with the SMPL model. Any 3D tool is possible to create this.
