### ISSUE TITLE
how to get different poses in the result?

### ISSUE THREAD

**Issue by lemon1220** [thmoa/tex2shape#15]
hello, thmoa:
thanks for your program!! when i look around this paper ,I find the different pose in the experiment part, Can you how can I get the result with poses? I run the pragram with no pose before. looking for your  reply，thanks
![Tex2 Shape Detailed Full Human Body Geometry From a Single Image](https://user-images.githubusercontent.com/52917659/111024748-6e090380-841b-11eb-9977-eed5903ed1e0.jpg)

the bellow is my result
![图片1](https://user-images.githubusercontent.com/52917659/111024768-81b46a00-841b-11eb-9727-3d5354fead16.jpg)

**Comment by lemon1220** [comment]
@thmoa @

**Comment by thmoa** [comment]
Please carefully read the paper. Tex2Shape is always reconstructing in rest pose. You can set poses by parameterizing the underlaying SMPL model. See SMPL code and paper for details.
