### ISSUE TITLE
Generating UV textures from 3D pose detector

### ISSUE THREAD

**Issue by mhq6634** [thmoa/tex2shape#16]
Hi, could you share the code for generating UV textures from HMR output as shown in Figure 7 in the paper? I couldn't find online how to do this. Thank you

**Comment by thmoa** [comment]
Render mesh with UV coordinates as vertex-colors. Perform the same sampling as for DensePose (without the Densepose to SMPL conversion).

Sorry I don't have access to the code anymore.

**Comment by mhq6634** [comment]
Could you share how to render the mesh with uniform lighting (instead of point lights) using OpenGL? I couldn't find much documentation and have no clue how to do this. Right now my output looks like this (after setting the vertex-colors as UV coordinates):
![image](https://user-images.githubusercontent.com/6861043/117331335-3e312600-aec9-11eb-8306-e78929f1dda5.png)
