### ISSUE TITLE
UV map details

### ISSUE THREAD

**Issue by xyyeah** [thmoa/tex2shape#17]
HI, thanks for the exciting job. I tried to extract an UV map of an example image based on DensePose, the output is slightly different with the corresponding example UV map, but the resulting 3D model is much worse than that of examples. Could you please share some details of the DensePose ? (for example, the backbone models listed in the [Model Zoos](https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/DENSEPOSE_IUV.md#ModelZoo)) Or, did i miss something to get this bad result? @thmoa Hope to get a reply, thanks.
![image](https://user-images.githubusercontent.com/90754199/147540998-722ce013-5be1-4314-9222-2ab43b7cb17f.png)

**Comment by thmoa** [comment]
I cannot remember the DensePose version that has been used. Look up which version was the current at the time of the release of this repo.
