### ISSUE TITLE
Why do all the results have the same pose?

### ISSUE THREAD

**Issue by xiezhy6** [thmoa/tex2shape#2]
Hi,
why do the results of different input images in the same pose?

**Comment by thmoa** [comment]
Please refer to the paper: Our method is pose-independent. We only estimate shape.

**Comment by OOF-dura** [comment]
> Hi,
> why do the results of different input images in the same pose?

Hi~ @xiezhy6 @thmoa Sorry for bother. I want to know wts the version of tf and keras you are using? I am using tf1.15 and get the following error:
```
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_1/convolution}}]]
         [[output/BiasAdd/_701]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_1/convolution}}]]
0 successful operations.
0 derived errors ignored.

```

Thanks in advance!

**Comment by thmoa** [comment]
see `requirements.txt`

**Comment by lemon1220** [comment]
Sorry for bother, so how can I adjust the pose the same as image's?

**Comment by lemon1220** [comment]
I see the model pose is the same with the image's in the paper
