### ISSUE TITLE
what is the best visualizer to check the ourput obj and pkl files?

### ISSUE THREAD

**Issue by wine3603** [thmoa/tex2shape#3]
Hi, @thmoa , thanks a lot for providing this excellent work!
I installed and made it work with python3.7. 
Thus, which software can I use to see the result?

**Comment by thmoa** [comment]
Any 3D mesh viewer or 3D animation software can open and display obj files...

**Comment by wine3603** [comment]
Hi @thmoa ,Thanks for the fast reply! 
I can open it with meshlab, without colors.
How to visualize it with the colorful textures as in your papers?
