### ISSUE TITLE
How to generate dp_uv_lookup_256.npy?

### ISSUE THREAD

**Issue by sdxass** [thmoa/tex2shape#5]
Hi, thanks for your wonderful work!

I would like to ask how did you get the dp_uv_lookup_256.npy file? 
Look forward to your reply. 

Thank you!

**Comment by LiuXinqi12** [comment]
Hi, I also want to know how to generate DP_ uv_ lookup_ 256.npy？
Thank you!

**Comment by thmoa** [comment]
Each pixel in the UV map corresponds to a point on the 3D mesh. Each point on the 3D mesh has both SMPL and DP UV coordinates.

**Comment by unknownoperation** [comment]
But how did you divide square area to 24 parts? How did you choose scales?(for example, scale of the head is bigger, than scale f the body). Also, how did you match SMPL vertices and one of 24 classes?
It would be very interesting to know, thanks a lot!

**Comment by thmoa** [comment]
I use the standard artist made SMPL UV map.
