### ISSUE TITLE
UV map synthetization

### ISSUE THREAD

**Issue by fabinsch** [thmoa/tex2shape#6]
Great work! Thanks for providing a lot of interesting insights. I'm trying to train my own model and encounter some unclear parts for generating the ground truth displacement maps. Given your detailed registration of the SMPL to the scans, you "simply render detailed UV displacement and normal maps". Those "encode the free-form offsets, that are not part of SMPL". 

Does this mean you render uv maps from the default SMPL model, then your detailed registered SMPL model and then take the difference between those (called free-form offsets in your paper)? 

If my understanding of this is wrong, I would be very happy if you could provide some further information of how to reproduce uv displacements maps encoding free-form offsets to SMPL. Thank you!

**Comment by thmoa** [comment]
Please use the issues only for issues with the code. Thank you.

The displacement maps encode 3D offsets from the SMPL shape (in UV space), that cannot be modeled using the SMPL shape space.
